In [1]:
import numpy as np

In [2]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [6]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
np.arange(1,31,5)

array([ 1,  6, 11, 16, 21, 26])

In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.zeroes(10)

AttributeError: module 'numpy' has no attribute 'zeroes'

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [16]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [17]:
np.eye((10))

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.random.ramd(3,5)

AttributeError: module 'numpy.random' has no attribute 'ramd'

In [19]:
np.random.rand(3,5)

array([[0.89438628, 0.24958164, 0.66344907, 0.22452324, 0.9877588 ],
       [0.0393719 , 0.32107089, 0.0743887 , 0.41953726, 0.73886553],
       [0.6268128 , 0.11669727, 0.08189674, 0.45755434, 0.24034037]])

In [20]:
arr=np.random.radn(2,4)
arr

AttributeError: module 'numpy.random' has no attribute 'radn'

In [21]:
arr=np.random.randn(2,4)
arr

array([[-0.56536563,  1.29975068, -1.20428332,  2.32551647],
       [ 0.5046174 , -0.95076927,  1.03978312, -0.075718  ]])

In [22]:
np.random.randint(2,100)


48

In [23]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
rand_array=np.random.randint(0,100,20)
rand_array

array([96, 32, 20, 77, 82, 86, 61, 35, 29, 51, 64, 90, 33, 17, 71, 14,  4,
       24, 36, 38])

In [25]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [26]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [27]:
rand_array.max()

96

In [28]:
rand_array.argmax()

0

In [29]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a=np.random.rand(2,3)

In [32]:
a.T

array([[0.11081129, 0.83042147],
       [0.95924015, 0.09530935],
       [0.55553559, 0.48369866]])

In [33]:
sample_array=np.arnage(10,21)
sample_array

AttributeError: module 'numpy' has no attribute 'arnage'

In [34]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [35]:
sample_array[0]


10

In [36]:
sample_array[2:5]

array([12, 13, 14])

In [37]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [38]:
sample_array[0:7]

array([ 10, 100, 100, 100,  14,  15,  16])

In [39]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([ 10, 100, 100, 100,  14,  15,  16])

In [40]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

In [41]:
import numpy as np

In [42]:
sample_matrix=np.array({{50,20,1,23],[24,23,21,33],[56,76,24,7]}})
sample_matrix

SyntaxError: closing parenthesis ']' does not match opening parenthesis '{' (2002048786.py, line 1)

In [44]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [45]:
sample_matrix[1,2]

21

In [46]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [47]:
sample_matrix[2]

array([56, 76, 24,  7])